/* 학습모듈 데이터 입력 */
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('SW아키텍처');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('응용SW엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('임베디드SW엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('DB엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('NW엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('보안엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('UI/UX엔지니어링');
INSERT INTO BIT_SUBJ_MODS(TITL) VALUES('시스템SW엔지니어링');

/* 강사 회원 정보 등록 */
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('홍길동','111-1111','hong@bit.com','1111');
INSERT INTO BIT_TCHS(TNO) VALUES(1);
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('임꺽정','111-1112','leem@bit.com','1111');
INSERT INTO BIT_TCHS(TNO) VALUES(2);
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('유관순','111-1113','ryu@bit.com','1111');
INSERT INTO BIT_TCHS(TNO) VALUES(3);
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('김구','111-1114','kim@bit.com','1111');
INSERT INTO BIT_TCHS(TNO) VALUES(4);
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('안중근','111-1115','ahn@bit.com','1111');
INSERT INTO BIT_TCHS(TNO) VALUES(5);

/* 매니저 회원 정보 등록 */
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('김용','111-1116','kimy@bit.com','1111');
INSERT INTO BIT_MGRS(MGRNO,POSI) VALUES(6,'대리');
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('강소희','111-1117','kang@bit.com','1111');
INSERT INTO BIT_MGRS(MGRNO,POSI) VALUES(7,'주임');
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('장현진','111-1118','jang@bit.com','1111');
INSERT INTO BIT_MGRS(MGRNO,POSI) VALUES(8,'대리');
INSERT INTO BIT_MEMBS(MNM,TEL,EMAIL,PWD) VALUES('홍주형','111-1119','hongjh@bit.com','1111');
INSERT INTO BIT_MGRS(MGRNO,POSI) VALUES(9,'주임');








