/* OUTER 조인 응용 */

/* 문제1) 다음 결과를 리턴하는 SQL을 작성하라!
 * 교육과정명, 학습모듈명, 강사명, 강사이메일 
 */
/* step1 */
SELECT TITL
FROM BIT_COURS;

/* step2 */
SELECT CO.TITL, CM.SMNO, CM.TNO
FROM BIT_COURS CO JOIN BIT_CO_MODS CM ON CO.CONO = CM.CONO;

/* step3 */
SELECT 
  CO.TITL AS COURS_TITLE, 
  SM.TITL AS SUBJ_MOD_TITLE,
  CM.TNO
FROM BIT_COURS CO 
     JOIN BIT_CO_MODS CM ON CO.CONO = CM.CONO
     JOIN BIT_SUBJ_MODS SM ON CM.SMNO = SM.SMNO;

/* step4 */
SELECT 
  CO.TITL AS COURS_TITLE, 
  SM.TITL AS SUBJ_MOD_TITLE,
  M.MNM AS TEACH_NAME
FROM BIT_COURS CO 
     JOIN BIT_CO_MODS CM ON CO.CONO = CM.CONO
     JOIN BIT_SUBJ_MODS SM ON CM.SMNO = SM.SMNO
     JOIN BIT_MEMBS M ON CM.TNO = M.MNO;     

/* step5: 강사가 배정되지 않은 학습 모듈도 결과로 뽑아낸다. */
SELECT 
  CO.TITL AS COURS_TITLE, 
  SM.TITL AS SUBJ_MOD_TITLE,
  M.MNM AS TEACH_NAME
FROM BIT_COURS CO 
     JOIN BIT_CO_MODS CM ON CO.CONO = CM.CONO
     JOIN BIT_SUBJ_MODS SM ON CM.SMNO = SM.SMNO
     LEFT OUTER JOIN BIT_MEMBS M ON CM.TNO = M.MNO; 


     
     
     
     
     
